name: pdfoto_flutter
description: A multi-platform app for creating PDFs that showcase a set of photos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  file_selector: ^0.8.4+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  open_file: ^2.1.1
  path_provider: ^2.0.10
  pdfoto:
    path: ../pdfoto
  printing: ^5.9.1
  url_launcher: ^6.1.2

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
