name: Publish Web
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish_web:
    defaults:
      run:
        working-directory: packages/pdfoto_flutter

    runs-on: ubuntu-latest

    env:
      BUILD_DIR: ./build/web/
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
          flutter-version: 3.0.0

      - name: Install app dependencies
        run: flutter pub get

      - name: Enable web support
        run: flutter config --enable-web

      - name: Build
        run: flutter build web --release -t lib/main_production.dart

      # - name: Copy CNAME
      #   run: cp ./CNAME ${{ env.BUILD_DIR }}

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.BUILD_DIR }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: web_build
          path: ${{ env.BUILD_DIR }}
